import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {initReports,createReport} from './reports.mjs';import {retrieve} from './retrieval.mjs';import {readFileSync} from 'node:fs';
const pages=JSON.parse(readFileSync(new URL('../book/index.json',import.meta.url)));
for(const q of ['อธิบายพ้อยเตอร์หน่อย','พ้อยน์เตอร์','พอยเตอ','poiner','ponter'])test('pointer typo: '+q,()=>assert.deepEqual(retrieve(pages,q).map(p=>p.page),retrieve(pages,'พอยน์เตอร์').map(p=>p.page)));
for(const [q,canonical] of [['ฟังก์ชั่น','ฟังก์ชัน'],['ฟังชั่น','ฟังก์ชัน'],['ลุป','ลูป'],['อาเร','อาร์เรย์'],['funtion','function']])test('topic alias '+q,()=>assert.ok(retrieve(pages,q).some(p=>retrieve(pages,canonical).some(c=>c.page===p.page))));
test('unrelated Thai stays unmatched',()=>assert.equal(retrieve(pages,'อากาศวันนี้เป็นไง').length,0));
function fixture(){const db=new DatabaseSync(':memory:');db.exec("CREATE TABLE chats(id TEXT,owner TEXT,chapter INTEGER,mode TEXT);CREATE TABLE messages(id INTEGER,chat TEXT,role TEXT,content TEXT,sources TEXT);INSERT INTO chats VALUES('c','alice',7,'ask');INSERT INTO messages VALUES(1,'c','user','pointer?','[]'),(2,'c','assistant','answer','[]');");initReports(db);return db}
const payload={requestKey:'12345678-1234-4321-8765-123456789012',category:'search',detail:'Cannot find pointer',chatId:'c',messageId:2};
test('authorized snapshot and retry deduplication',()=>{const db=fixture();const a=createReport(db,'alice',payload);assert.deepEqual(createReport(db,'alice',payload),a);const rows=db.prepare('SELECT * FROM reports').all();assert.equal(rows.length,1);assert.equal(JSON.parse(rows[0].context).question,'pointer?');db.close()});
test('cannot report someone else conversation',()=>{const db=fixture();assert.throws(()=>createReport(db,'bob',payload),e=>e.status===404);assert.equal(db.prepare('SELECT count(*) n FROM reports').get().n,0);db.close()});
test('reject invalid category, detail and message',()=>{const db=fixture();for(const patch of [{category:'fake'},{detail:'x'},{detail:'x'.repeat(2001)},{requestKey:''},{messageId:99},{messageId:1}])assert.throws(()=>createReport(db,'alice',{...payload,...patch}));db.close()});
test('general report stores no conversation',()=>{const db=fixture();createReport(db,'bob',{...payload,chatId:undefined,messageId:undefined});assert.deepEqual(JSON.parse(db.prepare('SELECT context FROM reports').get().context),{});db.close()});
