'use client';
import {useState} from 'react';
import {MessageCircle,BookOpen,MessagesSquare,BookMarked,ArrowRight} from 'lucide-react';
const steps=[
 {title:'เริ่มจากคำถามของคุณ',icon:MessageCircle,description:'บอกเรื่องที่สงสัยด้วยภาษาของตัวเอง จะถามว่าโค้ดทำอะไร ขอเรียนพื้นฐาน หรือขอฝึกโจทย์ก็ได้',label:'คำถาม',example:'“if กับ else ต่างกันอย่างไร?”'},
 {title:'ค้นเนื้อหาที่เกี่ยวข้อง',icon:BookOpen,description:'ระบบค้นเนื้อหาจากหนังสือภาษา C ที่เตรียมไว้ เพื่อใช้เป็นบริบทประกอบคำตอบ ไม่ได้ค้นเว็บทั่วไปทุกครั้งที่ถาม',label:'เนื้อหาจากหนังสือ',example:'บทที่ 4 · การตัดสินใจด้วย if, else และ switch'},
 {title:'อธิบายตามโหมดที่เลือก',icon:MessagesSquare,description:'บริการ AI ช่วยเรียบเรียงคำอธิบายตามคำถามและโหมดการเรียน ตัวอย่างโค้ดใช้เมื่อช่วยให้เข้าใจเรื่องที่ถามได้ดีขึ้น',label:'แนวทางการอธิบาย',example:'if ทำงานเมื่อเงื่อนไขเป็นจริง ส่วน else ทำงานเมื่อเงื่อนไขไม่เป็นจริง'},
 {title:'อ่านที่มา แล้วลองทำต่อ',icon:BookMarked,description:'เมื่อคำตอบมีแหล่งอ้างอิง คุณเปิดหน้าหนังสือเพื่อตรวจสอบ ถามต่อในบทสนทนาเดิม แล้วนำโค้ดไปลองรันด้วยตัวเองได้',label:'เรียนต่อจากคำตอบ',example:'เปิดหนังสือหน้า 32–42 → ลองเขียนเงื่อนไขของคุณเอง'}
];
export function Journey(){const [active,setActive]=useState(0);const current=steps[active];return <section className="journey section-pad" aria-labelledby="journey-title"><div className="section-heading"><div><span className="section-tag">คำตอบมีทางให้เรียนต่อ</span><h2 id="journey-title">จากความสงสัย<br/>สู่ความเข้าใจที่มีที่มา</h2></div><p>กดดูแต่ละขั้นเพื่อรู้ว่าเพื่อนมังกรช่วยคุณอย่างไร ตั้งแต่รับคำถามจนถึงเปิดหนังสืออ่านต่อ</p></div><div className="journey-layout"><div className="journey-steps">{steps.map((step,i)=><button key={step.title} aria-pressed={i===active} aria-controls="journey-detail" onClick={()=>setActive(i)}><span className="step-number">{i+1}</span><step.icon size={21}/><span>{step.title}</span><ArrowRight size={18}/></button>)}</div><div id="journey-detail" className="journey-detail" aria-live="polite"><div className="journey-symbol" aria-hidden="true"><current.icon size={42}/><i/><i/></div><span className="journey-label">{current.label}</span><h3>{current.example}</h3><p>{current.description}</p></div></div><p className="journey-note">คำตอบ AI อาจคลาดเคลื่อน ควรตรวจสอบกับแหล่งอ้างอิง และทดลองโค้ดในเครื่องของคุณเอง</p></section>}
