"use client";
import {useRef,useState} from 'react';
import {ArrowLeft,ArrowRight,ArrowUpRight,MessageCircle,GraduationCap,Target,Code2,Check} from 'lucide-react';
export function Modes(){
 const track=useRef<HTMLDivElement>(null);const [active,setActive]=useState(0);
 function select(index:number){const el=track.current;if(!el)return;const card=el.children[index] as HTMLElement;el.scrollTo({left:card.offsetLeft-el.offsetLeft,behavior:document.documentElement.dataset.motion==='on'?'smooth':'instant'})}
 return <section className="modes-section section-pad" id="modes" aria-labelledby="modes-title">
 <div className="section-heading"><div><span className="section-tag">เพื่อนเรียนคนเดียว ช่วยได้สามแบบ</span><h2 id="modes-title">ติดตรงไหน<br/>เริ่มเรียนจากตรงนั้น</h2></div><p>อยากได้คำอธิบาย อยากเรียนพื้นฐาน หรืออยากลองทำเอง เลือกวิธีที่เหมาะกับคุณ แล้วดูตัวอย่างบทสนทนาด้านล่าง</p></div>
 <div className="mode-controls"><div className="mode-choices" aria-label="เลือกดูโหมดการเรียน">{['ถามคำถาม','ติวทีละขั้น','ฝึกทำโจทย์'].map((label,i)=><button key={label} aria-pressed={active===i} onClick={()=>select(i)}>{label}</button>)}</div><div className="mode-arrows"><button aria-label="โหมดก่อนหน้า" disabled={active===0} onClick={()=>select(active-1)}><ArrowLeft size={19}/></button><button aria-label="โหมดถัดไป" disabled={active===2} onClick={()=>select(active+1)}><ArrowRight size={19}/></button></div></div>
 <div ref={track} className="mode-track" tabIndex={0} aria-label="รายละเอียดสามโหมด เลื่อนซ้ายขวาหรือใช้ปุ่มเลือก" onFocusCapture={event=>{const target=event.target as HTMLElement;const card=target.closest('.mode-card') as HTMLElement|null;const el=track.current;if(!card||!el)return;el.scrollTo({left:card.offsetLeft-el.offsetLeft,behavior:'instant'});target.scrollIntoView({block:'nearest',inline:'nearest',behavior:'instant'})}} onScroll={()=>{const el=track.current;if(!el)return;let closest=0,distance=Infinity;Array.from(el.children).forEach((child,i)=>{const d=Math.abs((child as HTMLElement).offsetLeft-el.offsetLeft-el.scrollLeft);if(d<distance){distance=d;closest=i}});setActive(closest)}}>
   <article className="mode-card ask-card"><div className="mode-card-copy"><span className="mode-icon"><MessageCircle size={23}/></span><p className="mode-en" lang="en">Ask freely.</p><h3>ถามสิ่งที่สงสัย<br/>ให้เข้าใจตรงจุด</h3><p>ถามแนวคิด ความต่างของคำสั่ง หรือบทที่อยากอ่านต่อ แล้วค่อยถามต่อจากคำตอบเดิมได้</p><a href="#demo" onClick={()=>window.dispatchEvent(new CustomEvent('cc-demo-mode',{detail:0}))}>ดูตัวอย่างการถาม <ArrowUpRight size={17}/></a></div><div className="mode-visual ask-visual" aria-hidden="true"><div className="question-orbit">?</div><div className="visual-bubble">int กับ float ต่างกันยังไง?</div><div className="visual-answer"><Code2 size={23}/><span>เริ่มจากชนิดของข้อมูล<br/><b>แล้วค่อยดูตัวอย่างด้วยกัน</b></span></div></div></article>
   <article className="mode-card tutor-card"><div className="mode-card-copy"><span className="mode-icon"><GraduationCap size={24}/></span><p className="mode-en" lang="en">Understand deeply.</p><h3>ค่อย ๆ เรียน<br/>ทีละความเข้าใจ</h3><p>ให้บอทอธิบายทีละขั้น ถามกลับเพื่อเช็กความเข้าใจ และช่วยคลี่จุดที่ยังสับสน</p><a href="#demo" onClick={()=>window.dispatchEvent(new CustomEvent('cc-demo-mode',{detail:1}))}>ดูตัวอย่างการติว <ArrowUpRight size={17}/></a></div><div className="mode-visual tutor-visual" aria-hidden="true"><div className="code-step"><span>เริ่มต้น</span><code>int i = 1;</code></div><div className="code-step"><span>ตรวจเงื่อนไข</span><code>i &lt;= 3</code></div><div className="code-step"><span>เพิ่มค่าทีละ 1</span><code>i++</code></div><div className="step-beam"/></div></article>
   <article className="mode-card quiz-card"><div className="mode-card-copy"><span className="mode-icon"><Target size={24}/></span><p className="mode-en" lang="en">Learn by doing.</p><h3>ลองคิด ลองเขียน<br/>แล้วค่อยทบทวน</h3><p>ขอโจทย์ ส่งคำตอบที่ลองทำ แล้วรับคำแนะนำและคำอธิบายเฉลยตามขั้นตอนของโจทย์</p><a href="#demo" onClick={()=>window.dispatchEvent(new CustomEvent('cc-demo-mode',{detail:2}))}>ดูตัวอย่างการฝึก <ArrowUpRight size={17}/></a></div><div className="mode-visual quiz-visual" aria-hidden="true"><div className="target-rings"><span/><span/><span/><Check size={60}/></div><div className="quiz-label">ความเข้าใจ เริ่มจากการลงมือ</div></div></article>

 </div><div className="gallery-foot"><span>เลือกโหมดได้ตามเรื่องที่กำลังเรียน</span><span aria-live="polite">{active+1} / 3</span></div>
 </section>
}
