import {ArrowUpRight,ArrowDown,BookOpen,ChevronRight,Monitor,Download,Check,MessageCircle,GraduationCap,Target,Code2,Github,ExternalLink} from 'lucide-react';
import {DragonMark} from '../components/DragonMark';
import {Demo} from '../components/Demo';
import {Modes} from '../components/Modes';
import {Journey} from '../components/Journey';
import {Experience} from '../components/Experience';
const chapters=[['01','เริ่มต้นภาษา C','ภาษาโปรแกรมและผังงาน'],['02','วางพื้นฐาน','ตัวแปร ชนิดข้อมูล ตัวดำเนินการ'],['03','สื่อสารกับโปรแกรม','printf และ scanf'],['04','ตัดสินใจ','if, else และ switch'],['05','ทำงานซ้ำ','for, while และ do-while'],['06','จัดเก็บเป็นชุด','อาร์เรย์'],['07','เข้าใจหน่วยความจำ','พอยน์เตอร์และสตริง'],['08','รวมข้อมูล','struct และ typedef'],['09','แบ่งงานให้ฟังก์ชัน','พารามิเตอร์และการคืนค่า'],['10','รับค่าจากคำสั่ง','argc และ argv'],['11','อ่านและเขียนไฟล์','การจัดการไฟล์'],['12','ต่อยอดโปรเจกต์','การทำงานหลายไฟล์']];
export default function Page(){return <>
 <a className="skip-link" href="#main">ข้ามไปเนื้อหา</a>
 <header className="site-header"><a className="wordmark" href="#top" aria-label="C Companion หน้าแนะนำ"><span className="brand-dragon"><DragonMark/></span>C Companion<span className="brand-period">.</span></a><nav aria-label="เมนูหน้าแนะนำ"><a href="#learn">วิธีเรียน</a><a href="#demo">ลองดูตัวอย่าง</a><a href="#start">วิธีเริ่มใช้</a></nav><a className="header-cta" href="/chat/">เปิดห้องแชท <ArrowUpRight size={17}/></a></header>
 <main id="main">
  <section className="hero" id="top" aria-labelledby="hero-title">
   <div className="hero-grid" aria-hidden="true"/><div className="hero-orbit" aria-hidden="true"/><span className="hero-glyph" aria-hidden="true">{'{ }'}</span>
   <div className="hero-content"><p className="hero-intro"><span/>เพื่อนติวภาษา C ที่เริ่มจากคำถามของคุณ</p><h1 id="hero-title">เข้าใจภาษา C<br/>ทีละคำถาม<br/>ทีละก้าว<span className="hero-dot">.</span></h1><p className="hero-description">เพื่อนมังกรที่ช่วยอธิบายโค้ด พาคิดทีละขั้น และชวนฝึกทำโจทย์ พร้อมค้นเนื้อหาจากหนังสือภาษา C ให้คุณกลับไปอ่านต่อได้</p><div className="hero-actions"><a className="button button-primary" href="/chat/">เริ่มเรียนภาษา C <ArrowUpRight size={19}/></a><a className="text-link" href="#demo">ดูตัวอย่างก่อน <span className="link-circle"><ArrowDown size={16}/></span></a></div></div>
   <div className="hero-art" aria-label="มังกรเขียวสามมิติถือหนังสือ อยู่ในวงแหวนภาษา C"><div className="scene-fallback" aria-hidden="true"><div className="fallback-ring"/><div className="fallback-dragon"><DragonMark/></div></div><div id="dragon-scene" aria-hidden="true"/><span className="orbital-caption" aria-hidden="true">A little curiosity. A lot of possibility.</span><div className="glass-note note-code" aria-hidden="true"><span>hello, curiosity</span><code>while (curious) {'{'}<br/>　learn();<br/>{'}'}</code></div><div className="glass-note note-book" aria-hidden="true"><BookOpen size={19}/><span>มีคำถามเมื่อไร<br/><b>เริ่มจากตรงนั้นได้เลย</b></span></div></div>
   <div className="hero-bottom"><a href="#learn" className="scroll-cue"><span className="scroll-line"/>เลื่อนเพื่อทำความรู้จัก <ArrowDown size={14}/></a><div className="hero-facts"><span><b>12</b> บทเรียน</span><span><b>3</b> วิธีเรียน</span><span>เปิดใช้ได้ <b>ไม่ต้องสมัคร</b></span></div></div>
  </section>
  <section className="intro-section section-pad" id="learn" aria-labelledby="intro-title"><div className="intro-top"><span className="section-tag">จาก “ไม่เข้าใจ” สู่ “ลองทำได้”</span><span className="section-note">เรียนรู้ตามจังหวะของคุณ</span></div><div className="intro-columns"><h2 id="intro-title">อ่านโค้ดแล้วงง?<br/>ลองคุยให้เห็นภาพ</h2><div className="intro-copy"><p>เมื่อเจอโค้ดที่อ่านไม่ออก หรือโปรแกรมที่ทำงานไม่ตรงใจ การมีพื้นที่ให้ถามต่อ ลองผิด และค่อย ๆ ทบทวน ช่วยให้ก้าวต่อได้ง่ายขึ้น</p><p>C Companion เป็นผู้ช่วยเรียนภาษา C ที่ค้นเนื้อหาจากหนังสือ แล้วช่วยอธิบายตามคำถาม พร้อมแหล่งอ้างอิงให้กลับไปอ่านและตรวจสอบด้วยตัวเอง</p><a className="text-link" href="#modes">ค้นหาวิธีเรียนที่เข้ากับคุณ <ArrowDown size={17}/></a></div></div><div className="learning-ribbon"><div><Code2 size={24}/><strong>อ่านโค้ดให้เข้าใจ</strong><span>ถามเหตุผลของคำสั่งที่สงสัย</span></div><div><GraduationCap size={26}/><strong>เรียนตามจังหวะตัวเอง</strong><span>ขออธิบายใหม่หรือตัวอย่างเพิ่มได้</span></div><div><Target size={25}/><strong>ต่อยอดด้วยการลงมือ</strong><span>ฝึกโจทย์และทบทวนสิ่งที่เรียน</span></div></div></section>
  <Modes/>
  <section className="demo-section section-pad" id="demo" aria-labelledby="demo-title"><div className="section-heading"><div><span className="section-tag">เห็นภาพก่อนเริ่มคุย</span><h2 id="demo-title">บทสนทนาเล็ก ๆ<br/>ที่พาไปได้ไกลกว่าเดิม</h2></div><p>เลือกโหมดเพื่อดูตัวอย่างที่เตรียมไว้<br/>เมื่อพร้อม เปิดห้องแชทแล้วถามด้วยคำของคุณเอง</p></div><Demo/></section>
  <Journey/>
  <section className="book-section section-pad" id="book" aria-labelledby="book-title"><div className="book-intro"><div className="book-art" aria-hidden="true"><div className="book-shadow"/><div className="book-object"><div className="book-spine">C Companion</div><div className="book-cover"><span>C Companion</span><b>C</b><span>เปิดอ่าน · ทำความเข้าใจ · ลองเขียน</span><i/></div><div className="book-pages"/></div><span className="book-caption">หนังสือเล่มเดียวกัน ความเข้าใจที่ต่อยอดได้</span></div><div className="book-copy"><span className="section-tag">มีที่มาให้กลับไปอ่าน</span><h2 id="book-title">คุยให้เข้าใจ<br/>เปิดหนังสือไปด้วยกัน</h2><p>C Companion ใช้หนังสือภาษา C โดย Soradech Krootjohn เป็นแหล่งความรู้ ครอบคลุม 12 บท ตั้งแต่พื้นฐานจนถึงการจัดโปรเจกต์ เมื่อคำตอบมีแหล่งอ้างอิง กดเปิดหน้าหนังสือในห้องแชทเพื่ออ่านบริบทและตรวจสอบได้ทันที</p><a className="button button-secondary" href="/book.pdf" target="_blank" rel="noreferrer">เปิดหนังสือภาษา C <BookOpen size={18}/></a><small>คำตอบ AI อาจคลาดเคลื่อน ควรอ่านและตรวจสอบกับหนังสือเสมอ</small></div></div><div className="chapter-grid" aria-label="เนื้อหาทั้ง 12 บท">{chapters.map(([n,title,description],i)=><a className="chapter-item" key={n} href={'/book.pdf#page='+[6,15,28,37,48,55,61,72,80,90,96,109][i]} target="_blank" rel="noreferrer"><span>{n}</span><div><h3>{title}</h3><p>{description}</p></div></a>)}</div></section>
  <section className="start-section section-pad" id="start" aria-labelledby="start-title"><div className="section-heading"><div><span className="section-tag">พื้นที่เรียนรู้ ในแบบของคุณ</span><h2 id="start-title">เปิดเว็บแล้วเริ่มเลย<br/>หรือมีไว้บนเครื่องตัวเอง</h2></div><p>ทั้งสองแบบไม่ต้องสร้างบัญชีผู้ใช้<br/>เลือกให้เข้ากับวิธีเรียนและการใช้งานของคุณ</p></div><div className="start-options"><article className="start-option web-option"><Monitor size={30}/><span className="option-label">สำหรับเริ่มเรียนทันที</span><h3>ใช้งานผ่านเว็บ</h3><p>เปิดห้องแชท เลือกเรื่องที่สนใจ แล้วเริ่มถามได้ เหมาะกับคนที่อยากลองเรียนโดยไม่ติดตั้งโปรแกรม</p><ul><li><Check size={16}/>เปิดจากคอมพิวเตอร์หรือมือถือ</li><li><Check size={16}/>เลือกได้ทั้งถาม ติว และฝึกโจทย์</li><li><Check size={16}/>อ่านแหล่งอ้างอิงควบคู่กับคำตอบ</li></ul><a className="button button-primary" href="/chat/">เปิดห้องแชท <ArrowUpRight size={18}/></a></article><article className="start-option local-option"><Download size={30}/><span className="option-label">สำหรับพื้นที่เรียนของคุณเอง</span><h3>ติดตั้งบนเครื่อง</h3><p>ดาวน์โหลดโปรเจกต์และทำตามคู่มือ ใช้ Docker เพื่อเริ่มระบบ และตั้งค่าบริการ AI ของคุณเอง</p><ul><li><Check size={16}/>รองรับ Windows, macOS และ Linux</li><li><Check size={16}/>ประวัติอยู่ในระบบของเครื่องที่ติดตั้ง</li><li><Check size={16}/>มีคู่มือเริ่มต้นและอัปเดตระบบ</li></ul><a className="button button-secondary" href="/manual.pdf" target="_blank" rel="noreferrer">อ่านคู่มือติดตั้ง <BookOpen size={18}/></a><a className="github-link" href="https://github.com/s6702041610258/c-companion" target="_blank" rel="noreferrer"><Github size={16}/>ดูโปรเจกต์บน GitHub <ExternalLink size={13}/></a></article></div><p className="install-note">ติดตั้งเองไม่ได้หมายถึง AI ทำงานออฟไลน์เสมอไป การเชื่อมต่อและค่าใช้จ่ายขึ้นกับบริการ AI ที่คุณเลือกและตั้งค่า</p></section>
  <section className="faq-section section-pad" aria-labelledby="faq-title"><h2 id="faq-title">ก่อนเริ่ม มีอะไรควรรู้?</h2><div>{[['ต้องเขียนภาษา C เป็นก่อนหรือไม่?','เริ่มจากพื้นฐานได้ เลือกโหมดติวทีละขั้น แล้วบอกเรื่องที่ยังไม่เข้าใจ เช่น ตัวแปร เงื่อนไข หรือการทำซ้ำ'],['ตัวอย่างในหน้านี้คือคำตอบจริงจาก AI หรือไม่?','เป็นตัวอย่างบทสนทนาที่จัดเตรียมไว้เพื่ออธิบายวิธีใช้ระบบ ไม่ได้เรียก AI อัตโนมัติจากหน้าแนะนำ หากต้องการถามจริง ให้กดเปิดห้องแชท'],['บอทรันหรือตรวจคอมไพล์โค้ดให้ได้ไหม?','บอทช่วยอธิบายโค้ดและให้ข้อเสนอแนะ แต่ไม่มีเครื่องมือรันหรือคอมไพล์โค้ด คุณควรนำโค้ดไปทดลองในสภาพแวดล้อมภาษา C ของตัวเอง'],['ประวัติจะตามไปทุกเครื่องหรือไม่?','ประวัติแยกตามเซสชันของเบราว์เซอร์ ไม่มีระบบล็อกอินหรือซิงก์ข้ามเครื่องอัตโนมัติ การล้างคุกกี้อาจทำให้เข้าไม่ถึงประวัติเดิม']].map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></section>
  <section className="final-section"><div className="final-orbit" aria-hidden="true"/><div className="final-dragon" aria-hidden="true"><DragonMark/></div><p>คำถามต่อไปของคุณ อาจเป็นก้าวแรกที่สำคัญ</p><h2>ความเข้าใจครั้งต่อไป<br/>เริ่มจากคำถามของคุณ</h2><a className="button button-primary" href="/chat/">เริ่มคุยกับ C Companion <ArrowUpRight size={20}/></a><span>ไม่ต้องสมัครสมาชิก · เริ่มจากเรื่องที่สงสัยได้เลย</span></section>
 </main>
 <footer className="site-footer"><a className="wordmark" href="#top">C Companion<span className="brand-period">.</span></a><p>เพื่อนติวภาษา C ที่เรียนรู้ไปกับคุณ</p><div><a href="/manual.pdf" target="_blank" rel="noreferrer">คู่มือ</a><a href="https://github.com/s6702041610258/c-companion" target="_blank" rel="noreferrer">GitHub</a><a href="/chat/">ห้องแชท <ArrowUpRight size={14}/></a></div></footer>
 <Experience/>
 </>}
